# Generated by Django 4.1.1 on 2022-10-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('specialty', models.CharField(choices=[('Orthopedics', 'Ortho'), ('Family', 'Family')], default='Family', max_length=11)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
