name: Build and Push Docker Image to GCR

on:
  pull_request_target:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@3.10.0

      - name: Build and push
        uses: docker/build-push-action@6.18.0
        with:
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'platform-engineering-org/akka' }}
          tags: ghcr.io/${{ github.repository_owner }}/akka:latest
          platforms: linux/amd64,linux/arm64/v8

      - name: Scan image for vulnerabilities
        if: github.event_name == 'pull_request_target'
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/akka:latest
          format: table
          output: trivy-results.txt
          exit-code: 0
          ignore-unfixed: false
          severity: CRITICAL,HIGH

      - name: Upload scan result artifact
        if: github.event_name == 'pull_request_target'
        uses: actions/upload-artifact@4.6.2
        with:
          name: scan-results
          path: trivy-results.txt

      - name: Download scan result artifact
        if: github.event_name == 'pull_request_target'
        uses: actions/download-artifact@4.3.0
        with:
          name: scan-results
          path: .

      - name: Read scan results into output
        if: github.event_name == 'pull_request_target'
        id: read-scan
        run: |
          echo "scan_output<<EOF" >> $GITHUB_OUTPUT
          cat trivy-results.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post Trivy scan result as PR comment
        if: github.event_name == 'pull_request_target'
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### 🔒 Trivy Scan Results for `ghcr.io/${{ github.repository_owner }}/akka:latest`
            ```
            ${{ steps.read-scan.outputs.scan_output }}
            ```
