name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@4.2.2

      - name: Set up Python
        uses: actions/setup-python@5.6.0
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r dev-requirements.txt -r manager/requirements.txt

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Run unit tests with pytest
        run: python -m pytest

